//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UltimateFishBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UltimateFishBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CoreAudioApi {
            get {
                object obj = ResourceManager.GetObject("CoreAudioApi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;translation&gt;
        ///    &lt;frmCode&gt;
        ///        &lt;TITLE&gt;Thanks for using the UltimateFishBot&lt;/TITLE&gt;
        ///        &lt;LIBELLE_TITLE&gt;Relax... It&apos;s still free !&lt;/LIBELLE_TITLE&gt;
        ///        &lt;LIBELLE_DESC&gt;You&apos;ve used the Ultimate Fishbot {0} times. To continue using it; you need to visit the Fishbot website and enter the 3-5 digit code in the box below.  If a browser window didn&apos;t open, you can find it at www.fishbot.net/code.html - or click the link below.  I promise, it&apos;s quick and painless.&lt;/LIBELLE_DESC&gt;
        ///        &lt;LIBELLE_TRY_AGAIN&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fishIcon35x35 {
            get {
                object obj = ResourceManager.GetObject("fishIcon35x35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;translation&gt;
        ///    &lt;frmCode&gt;
        ///        &lt;TITLE&gt;Merci d&apos;utiliser l&apos;UltimateFishBot&lt;/TITLE&gt;
        ///        &lt;LIBELLE_TITLE&gt;Relax... C&apos;est toujours gratuit !&lt;/LIBELLE_TITLE&gt;
        ///        &lt;LIBELLE_DESC&gt;
        ///          Vous avez utilisé UltimateFishBot {0} fois.
        ///          Pour continuer à l&apos;utiliser, vous devez visiter le site Fishbot et renseigner les 3 chiffres.
        ///          Si votre navigateur internet ne s&apos;est pas ouvert, cliquez simplement sur le lien ci-dessous.
        ///          Ne vous inquietez pas, c&apos;est est très rapide et sans douleu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Français {
            get {
                return ResourceManager.GetString("Français", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap offline {
            get {
                object obj = ResourceManager.GetObject("offline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online {
            get {
                object obj = ResourceManager.GetObject("online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap strip {
            get {
                object obj = ResourceManager.GetObject("strip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
